Enable max number of tries for SSH
to avoid getting into an infinite loop

diff --git a/mkmacvm b/mkmacvm
--- a/mkmacvm
+++ b/mkmacvm
@@ -625,26 +625,41 @@ sshIsRunning() {
 	nc -z "$VM_IPADDRESS" 22 >"$DEBUGOUT" 2>&1
 }
 waitForSsh() {
+	tries=30
 	until sshIsRunning; do
+		tries="$((tries - 1))"
+		if [ "0" -ge "$tries" ]; then
+			echo "VM SSH port is not reachable" >&2
+			return 1
+		fi
 		sleep 5
 	done
 }
 waitForSshKey() {
+	tries=30
+	success=""
 	# Use -t here to allocate a terminal so it's logged in system.log and the
 	# installer program can tell that we logged on
-	until {
-		sudo -u "$USERNAME" \
+	while [ 0 -lt "$tries" ] && [ -z "$success" ]; do
+		if sudo -u "$USERNAME" \
 			ssh -t -o StrictHostKeyChecking=no \
 			-o ConnectTimeout=5 "$VM_HOSTNAME" \
-			true
-	} >"$DEBUGOUT" 2>&1; do
-		sleep 5
+			true; then
+			success=yes
+		else
+			tries="$((tries - 1))"
+			sleep 5
+		fi
 	done
+	if [ -z "$success" ]; then
+		echo "Unable to connect to virtual machine via SSH" >&2
+		return 1
+	fi
 }
-waitForSsh # which ensures the hostname is found and has port 22 open
+waitForSsh || exit 1 # which ensures the hostname is found and has port 22 open
 echo "Setting up local ssh access..." >"$VERBOSEOUT"
-{ sudo -u "$USERNAME" ssh-keygen -R "$VM_HOSTNAME"; } >"$DEBUGOUT"
-waitForSshKey
+{ sudo -u "$USERNAME" ssh-keygen -R "$VM_HOSTNAME"; } >"$DEBUGOUT" 2>&1
+waitForSshKey || exit 1
 
 echo "Shutting down the virtual machine..." >"$VERBOSEOUT"
 while vmIsRunning; do
