Fix createinstall output

diff --git a/mkmacvm b/mkmacvm
--- a/mkmacvm
+++ b/mkmacvm
@@ -366,13 +366,17 @@ hdiutil attach "$INSTALLER_IMAGEFILE" -noverify -mountpoint "$INSTALLER_MOUNTPOI
 # createinstallmedia unfortunately sends normal progress output to stderr
 # this kludge allows us to monitor all output in debug mode but save the
 # output to display in all modes in case there's an error
-if ! createinstall_output="$(
-	"$CREATEINSTALL_PATH" --volume "$INSTALLER_MOUNTPOINT" --nointeraction 2>&1 \
-		| tee -a /dev/stderr
-)" 2>"$DEBUGOUT"; then
-	echo "$createinstall_output" >&2
-	echo "Unable to create the installation disk. Exiting." >&2
-	exit 1
+if [ -n "$DEBUG" ]; then
+	if ! "$CREATEINSTALL_PATH" --volume "$INSTALLER_MOUNTPOINT" --nointeraction >"$DEBUGOUT" 2>&1; then
+		echo "Unable to create installation disk. Exiting." >&2
+		exit 1
+	fi
+else
+	if ! createinstall_output="$("$CREATEINSTALL_PATH" --volume "$INSTALLER_MOUNTPOINT" --nointeraction 2>&1)"; then
+		echo "$createinstall_output" >&2
+		echo "Unable to create the installation disk. Exiting." >&2
+		exit 1
+	fi
 fi
 
 # note that at the end of this the volume is automatically remounted at
