Move more from test to test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -51,16 +51,90 @@ jobs:
           path: ~/github-runner-connect
       - name: checkout repository
         uses: actions/checkout@v3.0.2
+      - name: install Parallels Desktop
+        run: |
+          echo "Installing Parallels Desktop with Homebrew" >"$VERBOSEOUT"
+          if [ -z "${PARALLELS_KEY:=}" ]; then
+            echo "Error: 'PARALLELS_KEY' is not set; cannot activate Parallels Desktop" >&2
+            return 1
+          fi
+          if ! output="$({ sudo -u "$username" brew update; } 2>&1)"; then
+            echo "$output" >&2
+            # but don't necessarily fail here
+          fi
+          if ! output="$({ sudo -u "$username" brew install parallels --no-quarantine; } 2>&1)"; then
+            echo "$output" >&2
+            echo "Error: Unable to install Parallels Desktop" >&2
+            return 1
+          fi
+          # See, among others,
+          # https://www.rainforestqa.com/blog/macos-tcc-db-deep-dive and
+          # https://stackoverflow.com/questions/52706542/how-to-get-csreq-of-macos-application-on-command-line/57259004#57259004
+          echo "Adding permissions for Parallels Desktop" >"$VERBOSEOUT"
+          if ! csout="$(codesign -d -r - /Applications/Parallels\ Desktop.app 2>&1)" \
+            || ! csreq="$(
+              echo "$csout" \
+                | sed -E -e '/^designated =>/!d' -e 's/^designated => //' \
+                | csreq -r - -b /dev/stdout \
+                | xxd -p \
+                | tr -d '\n'
+            )"; then
+            echo "$csout" >&2
+            echo "$csreq" >&2
+            echo "Error: Unable to add required permissions to Parallels" >&2
+            return 1
+          fi
+          tccfile="/Users/$username/Library/Application Support/com.apple.TCC/TCC.db"
+          for perm in kTCCServiceCamera \
+            kTCCServiceMicrophone \
+            kTCCServiceSystemPolicyDesktopFolder \
+            kTCCServiceSystemPolicyDocumentsFolder \
+            kTCCServiceSystemPolicyDownloadsFolder \
+            kTCCServiceAccessibility; do
+            sqlite3 "$tccfile" \
+              "insert or replace into access (
+                service,
+                client,
+                client_type,
+                auth_value,
+                auth_reason,
+                auth_version,
+                csreq,
+                flags
+              ) values (
+                '$perm',
+                'com.parallels.desktop.console',
+                0,
+                2,
+                3,
+                1,
+                X'$csreq',
+                0
+              )"
+          done
+          echo "Activating Parallels Desktop"
+          if [ -z "${PRLSRVCTL:=$(getexec prlsrvctl)}" ]; then
+            echo "Error: Unable to find 'prlsrvctl'. Cannot activate Parallels Desktop." >&2
+            return 1
+          fi
+          if ! { sudo -u "$username" "$PRLSRVCTL" install-license -k "$PARALLELS_KEY"; } >"$DEBUGOUT"; then
+            error="Error: Unable to activate Parallels Desktop"
+            error="${error}\n       If necessary, revoke current activation keys at"
+            error="${error}\n       https://my.parallels.com"
+            printf "%s\n" "$error" >&2
+            return 1
+          fi
       - name: test mkmacvm
         if: ${{ ! inputs.debug }}
-        run: "$GITHUB_WORKSPACE/test"
+        run: sudo -E "$GITHUB_WORKSPACE/test"
         env:
           PARALLELS_KEY: ${{ secrets.PARALLELS_KEY }}
       - name: test mkmacvm in debug mode
         if: inputs.debug
-        run: "$GITHUB_WORKSPACE/test"
+        run: sudo -E "$GITHUB_WORKSPACE/test"
         env:
           PARALLELS_KEY: ${{ secrets.PARALLELS_KEY }}
+          DEBUG: y
       - name: take desktop screenshot
         uses: OrbitalOwen/desktop-screenshot-action@0.1
         if: failure() || inputs.debug
