Improve GitHub Actions debug workflow
- name steps
- better error messages for deactivating Parallels
- try to better enable SSH

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,31 +25,50 @@ jobs:
     runs-on: macos-12
     steps:
       - uses: actions/checkout@v3.0.2
-      - name: open ngrok connection
+      - name: enable SSH
         run: |
           sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
           brew install ngrok/ngrok/ngrok --no-quarantine
-          ngrok config add-authtoken "$NGROK_TOKEN"
+          ngrok tcp --authtoken "$NGROK_TOKEN" --log stdout --log-format logfmt 22 &
           mkdir -p "$HOME/.ssh"
-          ssh-keygen -t ecdsa -f "$HOME/.ssh/id_ecdsa"
-          echo "id_ecdsa:"
-          cat "$HOME/.ssh/id_ecdsa"
-          ngrok tcp 22 &
+          ssh-keygen -t rsa -f "$HOME/.ssh/id_rsa"
+          cat "$HOME/.ssh/id_rsa.pub" >> "$HOME/.ssh/authorized_keys"
+          chmod 0600 "$HOME/.ssh/"*
+          chmod 0700 "$HOME/.ssh"
+          echo SSH configured. Download connection script from Artifacts.
         env:
           NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
-      - name: test mkmacvm
+      - name: test mkmacvm in debug mode
         run: "$GITHUB_WORKSPACE/test"
         env:
           PARALLELS_KEY: ${{ secrets.PARALLELS_KEY}}
           DEBUG: y
-      - name: revoke key
+      - name: deactivate Parallels Desktop
         if: always()
         run: |
           if [ -e /usr/local/bin/prlsrvctl ]; then
-            /usr/local/bin/prlsrvctl deactivate-license \
-            || echo The license may have already been deactivated.
+            if ! output="$(/usr/local/bin/prlsrvctl deactivate-license 2>&1)"; then
+              if ! echo "$output" | grep 'activation key is invalid' >/dev/null; then
+                error="$output"
+                error="$error\nYou may be able to deactivate Parallels Desktop at"
+                error="$error\nhttps://my.parallels.com""
+                echo "$error" >&2
+                exit 1
+              else
+                echo "Unable to deactivate license; Parallels Desktop is already deactivated"
+              fi
+            else
+              echo "$output"
+            fi
+          else
+            error="Unable to deactivate Parallels Desktop: prlsrvctl not found" >&2
+            error="$error\nYou may be able to deactivate Parallels Desktop at"
+            error="$error\nhttps://my.parallels.com""
+            echo "$error" >&2
+            exit 1
           fi
-      - uses: OrbitalOwen/desktop-screenshot-action@0.1
+      - name: take desktop screenshot
+        uses: OrbitalOwen/desktop-screenshot-action@0.1
         if: always()
         with:
           file-name: "desktop.jpg"
